version: '3.6'
services:
  api:
    build: .
    image: group18/cs493finalproject
    restart: always
    ports:
      - 8000:8000
    environment:
      KEY: catsanddogs123
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: finalproject
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      PORT: 8000

  mysql:
    image: mysql:5
    restart: always
    volumes:
      - final-mysql:/var/lib/mysql
      - ./db-init/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: finalproject
      MYSQL_USER: username
      MYSQL_PASSWORD: password

volumes:
  final-mysql:
    name: finalproject-mysql-data
